import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db/prisma";
import { SectionType } from "@/types/project";

const SECTION_ORDER: SectionType[] = [
  "overview", "personas", "scope", "flows", "wireframes",
  "stack", "launch", "landingCopy", "buildMode",
];

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  try {
    const { projectId } = await params;
    const body = await req.json().catch(() => ({}));
    const exportType: "markdown" | "json" | "prompt" =
      body.exportType ?? "markdown";

    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        sections: { orderBy: { createdAt: "asc" } },
      },
    });

    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    type SectionRow = { sectionType: string; title: string; summary: string; contentJson: unknown };
    const sectionMap = new Map<string, SectionRow>(
      (project.sections as SectionRow[]).map((s) => [s.sectionType, s])
    );

    let content = "";

    if (exportType === "json") {
      const output: Record<string, unknown> = {
        project: {
          id: project.id,
          title: project.title,
          rawIdea: project.rawIdea,
          targetUser: project.targetUser,
          goal: project.goal,
          skillLevel: project.skillLevel,
        },
        sections: {},
      };
      for (const type of SECTION_ORDER) {
        const s = sectionMap.get(type);
        if (s) (output.sections as Record<string, unknown>)[type] = s.contentJson;
      }
      content = JSON.stringify(output, null, 2);
    } else if (exportType === "prompt") {
      content = buildClaudePrompt(project, sectionMap);
    } else {
      content = buildMarkdown(project, sectionMap, SECTION_ORDER);
    }

    // Persist export
    await prisma.projectExport.create({
      data: { projectId, exportType, content },
    });

    return NextResponse.json({ success: true, content, exportType });
  } catch (err) {
    console.error("[POST /api/projects/:id/export]", err);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}

function buildMarkdown(
  project: { title: string; rawIdea: string; goal?: string | null; targetUser?: string | null },
  sectionMap: Map<string, { title: string; summary: string; contentJson: unknown }>,
  order: SectionType[]
): string {
  const lines: string[] = [
    `# ${project.title}`,
    ``,
    `> ${project.rawIdea}`,
    ``,
    project.goal ? `**Goal:** ${project.goal}` : "",
    project.targetUser ? `**Target User:** ${project.targetUser}` : "",
    ``,
    `---`,
    ``,
  ];

  for (const type of order) {
    const s = sectionMap.get(type);
    if (!s) continue;
    lines.push(`## ${s.title}`);
    lines.push(`_${s.summary}_`);
    lines.push(``);
    lines.push("```json");
    lines.push(JSON.stringify(s.contentJson, null, 2));
    lines.push("```");
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`_Generated by FORGE AI_`);
  return lines.filter((l) => l !== undefined).join("\n");
}

function buildClaudePrompt(
  project: {
    title: string;
    rawIdea: string;
    goal?: string | null;
    skillLevel?: string | null;
    preferredStack?: string | null;
    targetUser?: string | null;
  },
  sectionMap: Map<string, { contentJson: unknown }>
): string {
  const overview = sectionMap.get("overview")?.contentJson as Record<string, string> | undefined;
  const stack = sectionMap.get("stack")?.contentJson as Record<string, string> | undefined;
  const buildMode = sectionMap.get("buildMode")?.contentJson as {
    claudePrompt?: string;
    screens?: Array<{ name: string }>;
    roadmap?: Array<{ week: number; focus: string }>;
  } | undefined;

  // If build mode has a claudePrompt, return that directly
  if (buildMode?.claudePrompt) return buildMode.claudePrompt;

  const lines: string[] = [
    `# Build Prompt: ${project.title}`,
    ``,
    `You are building **${project.title}**.`,
    ``,
    `## Product`,
    project.rawIdea,
    ``,
  ];

  if (overview?.oneLineSummary) {
    lines.push(`**Summary:** ${overview.oneLineSummary}`);
    lines.push(``);
  }

  if (project.targetUser) {
    lines.push(`**Target User:** ${project.targetUser}`);
  }

  if (stack) {
    lines.push(``, `## Recommended Stack`);
    if (stack.frontend) lines.push(`- Frontend: ${stack.frontend}`);
    if (stack.backend) lines.push(`- Backend: ${stack.backend}`);
    if (stack.database) lines.push(`- Database: ${stack.database}`);
    if (stack.auth) lines.push(`- Auth: ${stack.auth}`);
    if (stack.infra) lines.push(`- Infra: ${stack.infra}`);
  }

  if (buildMode?.screens?.length) {
    lines.push(``, `## Screens to Build`);
    for (const s of buildMode.screens) lines.push(`- ${s.name}`);
  }

  if (buildMode?.roadmap?.length) {
    lines.push(``, `## Build Roadmap`);
    for (const r of buildMode.roadmap) lines.push(`- Week ${r.week}: ${r.focus}`);
  }

  lines.push(``, `## Instructions`, `Build the MVP following the above spec. Start with setup, then auth, then core flows.`);

  return lines.join("\n");
}
